export { CHANGELOG } from './data/core';
import { Tool, Project } from './types';

export const TOOLS: Tool[] = [
  // SINGLE-FILE APPS & TOOLS
  {
    id: 'slime_factory_tycoon',
    name: 'Slime Factory Tycoon 🟢',
    category: 'start',
    description: 'Production-ready open-source Roblox idle tycoon & interactive web demo with pets engine, offline earnings & balance simulator.',
    url: 'https://dlinacre.github.io/slime-factory-tycoon/',
    host: 'dlinacre.github.io/slime-factory-tycoon',
    searchKeywords: 'slime factory tycoon roblox luau game idle simulator pets rebirth linacre',
    tag: 'Game · Live'
  },
  {
    id: 'circuit',
    name: 'Circuit 🔌',
    category: 'start',
    description: 'Rotate every wire until the whole grid lights up — procedural puzzles with a shared daily grid and par.',
    url: '/games/circuit',
    host: 'linacre.site/games',
    searchKeywords: 'circuit puzzle wire rotate grid daily arcade game linacre',
    tag: 'Game · Live'
  },
  {
    id: 'decrypt',
    name: 'Decrypt 🔓',
    category: 'start',
    description: 'Crack a four-symbol code in eight guesses — pure deduction with a daily streak and challenge links.',
    url: '/games/decrypt',
    host: 'linacre.site/games',
    searchKeywords: 'decrypt code logic mastermind deduction daily streak game linacre',
    tag: 'Game · Live'
  },
  {
    id: 'pulse',
    name: 'Pulse 🫀',
    category: 'start',
    description: 'Repeat the signal, one step longer each round — solo memory game or pass-and-play duel.',
    url: '/games/pulse',
    host: 'linacre.site/games',
    searchKeywords: 'pulse memory simon signal repeat duel daily game linacre',
    tag: 'Game · Live'
  },
  {
    id: 'trigger',
    name: 'Trigger ⚡',
    category: 'start',
    description: 'Two-player reflex game on one phone — green means go, amber is a trap. First to five wins.',
    url: '/games/trigger',
    host: 'linacre.site/games',
    searchKeywords: 'trigger reflex two player reaction game duel linacre',
    tag: 'Game · Live'
  },
  {
    id: 'gridlock',
    name: 'Gridlock 〰️',
    category: 'start',
    description: 'Draw a line, close a square, go again — pass-and-play or take on a chain-aware AI.',
    url: '/games/gridlock',
    host: 'linacre.site/games',
    searchKeywords: 'gridlock dots and boxes strategy two player ai game linacre',
    tag: 'Game · Live'
  },
  {
    id: 'facerater_ai',
    name: 'FaceRater AI ✨',
    category: 'start',
    description: 'Neutral aesthetic face scoring & instant AI reasoning card with shareable TikTok/Instagram 1080x1350 layouts.',
    url: 'https://ai-face-rater-next.vercel.app',
    host: 'ai-face-rater-next.vercel.app',
    searchKeywords: 'face rater ai aesthetic scoring vision selfie ratings viral tiktok vercel dlinacre',
    tag: 'App · Live'
  },
  {
    id: 'pixel_heist',
    name: 'Pixel Heist 🚨',
    category: 'start',
    description: 'Cyberpunk stealth heist arcade game built with React 19 & Phaser 3. Procedural neon vaults, guard AI, laser grids & HMAC high scores.',
    url: 'https://dlinacre.github.io/pixel-heist/',
    host: 'dlinacre.github.io/pixel-heist',
    searchKeywords: 'pixel heist game stealth phaser cyberpunk arcade arcade game procedural lockpicking dlinacre github pages',
    tag: 'Game · Live'
  },
  {
    id: 'grumpy_guy_ai',
    name: 'Grumpy Guy AI ಠ_ಠ',
    category: 'start',
    description: 'Your disagreeable AI copilot — motivation, with complaints. Reality checks with custom tones & speech synthesis.',
    url: 'https://dlinacre.github.io/grumpy-guy-ai/',
    host: 'dlinacre.github.io/grumpy-guy-ai',
    searchKeywords: 'grumpy guy ai motivation copilot disagreeable reality check react vite speak synthesis dlinacre github pages',
    tag: 'App · Live'
  },
  {
    id: 'poke_flip_ai',
    name: 'PokéFlip AI',
    category: 'start',
    description: 'Real-time arbitrage, high-frequency card flipping & predictive TCG valuation engine powered by Gemini.',
    url: 'https://pok-flip-ai.vercel.app',
    host: 'pok-flip-ai.vercel.app',
    searchKeywords: 'poke flip ai pokemon tcg arbitrage valuation high frequency trading gemini cardmarket ebay',
    tag: 'App · Live'
  },
  {
    id: 'nic_food_decider',
    name: "Nic's Food Decider",
    category: 'start',
    description: 'One-click decision engine for dinner — cook or takeaway with weighted preferences & dietary filters.',
    url: 'https://nic-food-decider.vercel.app',
    host: 'nic-food-decider.vercel.app',
    searchKeywords: 'nic food decider dinner meal decision takeaway cook recipes flask vercel',
    tag: 'App · Live'
  },
  {
    id: 'payhip_scraper',
    name: 'PayHip Scraper',
    category: 'start',
    description: 'Digital product intelligence for Payhip: live marketplace scraping, deterministic scoring & Arena.ai prompts.',
    url: 'https://payhipscraper-production.up.railway.app',
    host: 'payhipscraper-production.up.railway.app',
    searchKeywords: 'payhip scraper digital product intelligence market research arena ai node railway',
    tag: 'App · Live'
  },
  {
    id: 'opagent',
    name: 'Personal OP Agent',
    category: 'start',
    description:
      'Zero-setup client-side AI workspace & prompt controller. Runs 100% in your browser.',
    url: '/tools/opagent.html',
    host: 'linacre.site/tools/opagent.html',
    searchKeywords: 'opagent personal ai agent prompt workspace single file html',
    tag: 'App · Live',
  },
  {
    id: 'arena_audit',
    name: 'Arena Audit Prompt Builder',
    category: 'start',
    description:
      'Universal browser audit prompt generator for engineering, UX, security, and performance reviews.',
    url: 'https://dlinacre.github.io/a-audit/',
    host: 'dlinacre.github.io/a-audit',
    searchKeywords: 'arena audit prompt builder security performance code quality',
    tag: 'App · Live',
  },
  {
    id: 'apk_hub',
    name: 'Android APK Launch Hub',
    category: 'start',
    description:
      "Quick launcher and download index for David's Android utilities and debloat tools.",
    url: '/tools/apk-hub.html',
    host: 'linacre.site/tools/apk-hub.html',
    searchKeywords: 'apk hub launcher android utilities uninstaller',
    tag: 'App · Live',
  },

  // START & IDE
  {
    id: 'vscode',
    name: 'VS Code',
    category: 'start',
    description: 'Gold-standard code editor with essential TypeScript, Git, and React extensions.',
    url: 'https://code.visualstudio.com',
    host: 'code.visualstudio.com',
    searchKeywords: 'vs code editor microsoft extensions vscode',
    tag: 'Free',
  },
  {
    id: 'github',
    name: 'GitHub',
    category: 'start',
    description:
      'Version control, open-source portfolio hosting, Actions CI/CD, and release management.',
    url: 'https://github.com/DLinacre',
    host: 'github.com/DLinacre',
    searchKeywords: 'github version control repos repositories git dlinacre',
    tag: 'Free',
  },
  {
    id: 'git',
    name: 'Git',
    category: 'start',
    description:
      'Fundamental CLI version control tool for tracking commits, branches, and releases.',
    url: 'https://git-scm.com',
    host: 'git-scm.com',
    searchKeywords: 'git version control cli terminal commandline',
    tag: 'Free',
  },

  // BUILD
  {
    id: 'react',
    name: 'React',
    category: 'build',
    description: 'Modern component-based UI library powering interactive browser tools and SPAs.',
    url: 'https://react.dev',
    host: 'react.dev',
    searchKeywords: 'react ui library javascript components frontend framework SPA vdom',
    tag: 'Free',
  },
  {
    id: 'vite',
    name: 'Vite',
    category: 'build',
    description: 'Lightning-fast dev server and frontend build tool with hot module replacement.',
    url: 'https://vitejs.dev',
    host: 'vitejs.dev',
    searchKeywords: 'vite build tool dev server bundler HMR esbuild rollup',
    tag: 'Free',
  },
  {
    id: 'tailwind',
    name: 'Tailwind CSS',
    category: 'build',
    description: 'Utility-first CSS framework for rapid responsive layouts and consistent styling.',
    url: 'https://tailwindcss.com',
    host: 'tailwindcss.com',
    searchKeywords: 'tailwind css utility styling layout responsive',
    tag: 'Free',
  },
  {
    id: 'python',
    name: 'Python',
    category: 'build',
    description:
      'Versatile language used for backend services, automation scripts, and CLI toolchains.',
    url: 'https://python.org',
    host: 'python.org',
    searchKeywords: 'python backend automation scripting CLI fast-api',
    tag: 'Free',
  },
  {
    id: 'kotlin',
    name: 'Kotlin & Android SDK',
    category: 'build',
    description:
      'Native Android development for utilities like Linacre Uninstaller and DKMA Monster.',
    url: 'https://developer.android.com',
    host: 'developer.android.com',
    searchKeywords: 'kotlin android mobile app development sdk',
    tag: 'Free',
  },
  {
    id: 'dexie',
    name: 'Dexie / IndexedDB',
    category: 'build',
    description:
      'Local-first browser database wrapper for fast offline storage without backend dependence.',
    url: 'https://dexie.org',
    host: 'dexie.org',
    searchKeywords: 'dexie indexeddb storage local-first database offline',
    tag: 'Free',
  },

  // DEPLOY
  {
    id: 'vercel',
    name: 'Vercel',
    category: 'deploy',
    description: 'Global edge hosting platform with automated GitHub deployment previews and SSL.',
    url: 'https://vercel.com',
    host: 'vercel.com',
    searchKeywords: 'vercel deploy hosting edge serverless static analytics',
    tag: 'Free',
  },
  {
    id: 'github_pages',
    name: 'GitHub Pages',
    category: 'deploy',
    description: 'Free static hosting directly from GitHub repositories for web guides and games.',
    url: 'https://pages.github.com',
    host: 'pages.github.com',
    searchKeywords: 'github pages static hosting deploy web docs',
    tag: 'Free',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    category: 'deploy',
    description: 'DNS management, edge workers, and CDN caching for domain performance.',
    url: 'https://cloudflare.com',
    host: 'cloudflare.com',
    searchKeywords: 'cloudflare cdn dns workers security edge',
    tag: 'Free',
  },
];

export const MANUAL_PROJECTS: Project[] = [
  {
    name: 'Bonny Bats 🦇',
    authorHandle: '@DLinacre',
    badgeLabel: 'Web · Live App',
    actionType: 'open',
    bannerImage: '/banners/bonny-bats.webp',
    category: 'build',
    description:
      'A friendly, beautifully illustrated guide to bats in buildings — spotting them, staying safe, the law, and humane one-way exclusion. Named after my mum, Bonny.',
    url: 'https://dlinacre.github.io/bonny-bats/',
    host: 'dlinacre.github.io/bonny-bats',
    tag: 'Web Guide · Live',
    role: 'Designer and frontend engineer',
    challenges:
      'Make a genuinely useful, trustworthy guide about a legally protected species — while keeping it easy for non-experts (and my mum) to read and use.',
    solution:
      'One self-contained HTML file with clear step-by-step sections, live seasonal advice, readability controls (text size, high contrast) and a print-friendly layout.',
    tech: ['HTML', 'CSS', 'JavaScript', 'SVG', 'GitHub Pages'],
    liveUrl: 'https://dlinacre.github.io/bonny-bats/',
    repoUrl: 'https://github.com/DLinacre/bonny-bats',
    live: true,
  },
  {
    name: 'KushCloud 🌿',
    authorHandle: '@DLinacre',
    badgeLabel: 'Game · Live App',
    actionType: 'play',
    bannerImage: '/banners/kushcloud.webp',
    category: 'design',
    description:
      'Chill one-tap browser arcade flyer with four worlds, power-ups, synthesized Web Audio sound, unlockable cosmetics, and global leaderboard.',
    url: 'https://dlinacre.github.io/KushCloud/',
    host: 'dlinacre.github.io/KushCloud',
    tag: 'Browser Game · Live',
    role: 'Game designer and frontend engineer',
    challenges:
      'Deliver responsive arcade controls, progression, sound, and visual variety without relying on heavy external game assets.',
    solution:
      'Used Canvas 2D, Web Audio, deterministic game state, adaptive quality, keyboard/touch controls, and a PWA-ready React shell.',
    tech: ['React', 'TypeScript', 'Vite', 'Canvas 2D', 'Web Audio API'],
    liveUrl: 'https://dlinacre.github.io/KushCloud/',
    repoUrl: 'https://github.com/DLinacre/KushCloud',
    live: true,
  },
  {
    name: 'Tap & Slap 🥊',
    authorHandle: '@DLinacre',
    badgeLabel: 'Game · Live App',
    actionType: 'play',
    bannerImage: '/banners/tap-and-slap.webp',
    artwork: '/projects/tap-and-slap.webp',
    category: 'design',
    description:
      'A dance-mat beat \'em up: tap to kill enemies exactly on the beat. Four neon lanes, combo multipliers up to 8×, original procedural synthwave fight music, daily challenges and a live leaderboard — keyboard or touch, free in the browser.',
    url: 'https://tap-and-slap.vercel.app',
    host: 'tap-and-slap.vercel.app',
    tag: 'Rhythm brawler · Live',
    role: 'Creator and lead developer',
    challenges:
      'Making rhythm precision feel honest: latency-aware audio scheduling, lane-accurate hit testing with pads on the visible hit line, and feedback for every tap — so PERFECT is achievable by ear, not luck.',
    solution:
      'A Next.js 15 + Phaser 3 + TypeScript monolith with a BeatClock-anchored Web Audio scheduler, procedural seeded levels, Prisma + PostgreSQL leaderboards, Auth.js accounts and Playwright E2E coverage.',
    tech: ['Next.js 15', 'Phaser 3', 'TypeScript', 'Web Audio API', 'Prisma', 'PostgreSQL', 'Auth.js'],
    liveUrl: 'https://tap-and-slap.vercel.app',
    repoUrl: 'https://github.com/DLinacre/tap-and-slap',
    live: true,
  },
  {
    name: 'FaceRater AI ✨',
    authorHandle: '@DLinacre',
    badgeLabel: 'AI App · Live',
    actionType: 'open',
    bannerImage: '/banners/facerater.webp',
    artwork: '/projects/facerater.webp',
    category: 'build',
    description:
      'Neutral aesthetic face scoring & instant AI reasoning card generator with shareable 1080×1350 social media layout and live vision metrics.',
    url: 'https://ai-face-rater-next.vercel.app/',
    host: 'ai-face-rater-next.vercel.app',
    tag: 'AI App · Live',
    role: 'Creator and full-stack engineer',
    challenges:
      'Providing instantaneous face aesthetic scoring without complex backend server infrastructure.',
    solution:
      'Built a Next.js 15 app leveraging Gemini 2.5 Flash Vision API for facial landmark analysis, symmetry scoring, and instant social card rendering.',
    tech: ['Next.js 15', 'Gemini 2.5 Flash', 'React 19', 'Tailwind CSS'],
    liveUrl: 'https://ai-face-rater-next.vercel.app/',
    live: true,
  },
  {
    name: 'PokéFlip AI 🎴',
    authorHandle: '@DLinacre',
    badgeLabel: 'AI & Mobile · Live',
    actionType: 'open',
    bannerImage: '/banners/pokeflip-ai.webp',
    artwork: '/projects/pokeflip.webp',
    category: 'build',
    description:
      'Real-time Pokémon TCG card arbitrage, valuation & predictive market scanner utilizing Gemini models, live TCGplayer prices, and opportunity radar.',
    url: 'https://pok-flip-ai.vercel.app',
    host: 'pok-flip-ai.vercel.app',
    tag: 'AI & Mobile · Live',
    role: 'Lead developer and market algorithm engineer',
    challenges:
      'Identifying underpriced Pokémon card listings in real-time across multiple marketplace feeds.',
    solution:
      'Integrated Gemini model reasoning with live market pricing feeds, profit margin calculation engines, and mobile-friendly alert radar.',
    tech: ['React Native', 'Gemini AI', 'TypeScript', 'Tailwind CSS'],
    repoUrl: 'https://github.com/DLinacre/Pok-Flip-AI',
    live: true,
  },
  {
    name: 'Smart Mail AI ✉️',
    authorHandle: '@DLinacre',
    badgeLabel: 'AI App · Live',
    actionType: 'open',
    bannerImage: '/banners/smart-mail.webp',
    category: 'build',
    description:
      'AI-powered unified inbox (Google Gemini) — smart email categorisation, importance detection & multi-account summary generator.',
    url: 'https://smart-mail-gamma.vercel.app',
    host: 'smart-mail-gamma.vercel.app',
    tag: 'AI App · Live',
    role: 'Full-stack AI developer',
    challenges:
      'Sorting thousands of incoming emails by urgency and context without exposing private credentials.',
    solution:
      'Built a client-side inbox scanner powered by Gemini API, importance classification, tag filtering, and mobile Capacitor wrapper.',
    tech: ['React', 'TypeScript', 'Google Gemini API', 'Capacitor'],
    liveUrl: 'https://smart-mail-gamma.vercel.app',
    repoUrl: 'https://github.com/DLinacre/smart-mail',
    live: true,
  },
  {
    name: 'Dragon Rush Heroes 🐉',
    authorHandle: '@DLinacre',
    badgeLabel: 'Game · Live App',
    actionType: 'play',
    bannerImage: '/banners/dragon-rush-heroes.webp',
    category: 'design',
    description:
      'Original anime action-RPG card battler — 464 fighters, real-time Arts combat, provably-fair gacha summons, Web Audio soundtracks, and offline save.',
    url: 'https://dlinacre.github.io/dragon-rush-heroes/',
    host: 'dlinacre.github.io/dragon-rush-heroes',
    tag: 'Action RPG · Live',
    role: 'Game creator and audio engineer',
    challenges:
      'Building a feature-packed action RPG card game with hundreds of characters, particle FX, and real-time battle logic.',
    solution:
      'Engineered an HTML5 Canvas 2D engine with Web Audio synth soundtrack, Gacha RNG verification, and local state persistence.',
    tech: ['Vanilla JS', 'Canvas 2D', 'Web Audio', 'Node.js'],
    liveUrl: 'https://dlinacre.github.io/dragon-rush-heroes/',
    repoUrl: 'https://github.com/DLinacre/dragon-rush-heroes',
  },
  {
    name: 'Whole-Home Ad Blocker',
    artwork: '/projects/whole-home-adblocker.svg',
    category: 'deploy',
    description: 'A one-click Windows installer that turns an always-on PC into an AdGuard Home network ad blocker — interactive setup wizard, live blocking dashboard, preloaded filter lists and encrypted DNS.',
    url: 'https://github.com/DLinacre/whole-home-adblocker',
    host: 'github.com/DLinacre/whole-home-adblocker',
    tag: 'Open Source · MIT',
    role: 'Product designer and developer',
    challenges: 'Network-wide ad blocking (Pi-hole / AdGuard Home) normally demands DNS knowledge, YAML editing and Docker familiarity — far out of reach for non-technical households.',
    solution: 'Wrapped AdGuard Home in Docker behind an interactive PowerShell setup wizard: auto-installs Docker Desktop, asks three plain-English questions (dashboard port, encrypted DNS provider incl. family mode, blocklist strength), bcrypt-seeds a ready-made config with three filter lists, self-heals port conflicts, schedules silent weekly updates, and ships router guides with UK ISP workarounds. Validated in CI with PSScriptAnalyzer and yamllint.',
    tech: ['PowerShell', 'Docker', 'AdGuard Home', 'Batch', 'GitHub Actions'],
    liveUrl: 'https://github.com/DLinacre/whole-home-adblocker',
    repoUrl: 'https://github.com/DLinacre/whole-home-adblocker',
    live: true,
  },
  {
    name: 'String & Band 🏹',
    category: 'build',
    description: 'An offline-first educational knowledge base on the history, materials and craft of archery equipment and slingshots: 18 long-form articles, a 44-material explorer with a live analysis engine, comparison lab, 49-term glossary and fuzzy search — all in one self-contained, dependency-free HTML file.',
    url: 'https://dlinacre.github.io/string-and-band/',
    host: 'dlinacre.github.io/string-and-band',
    tag: 'Featured · Live PWA',
    role: 'Creator, designer & sole developer',
    challenges: 'Delivering a premium, genuinely searchable reference — with radar charts, a command palette, fuzzy search and an interactive material rules engine — inside a single portable HTML file with zero dependencies and no build step, while hitting WCAG 2.2 AA and full offline support.',
    solution: 'Architected a data-driven single-file SPA in vanilla ES2025 with hand-rolled SVG radar and meter charts, a subsequence-scored fuzzy search engine over 107 indexed items, a category-driven material explorer with historical synergy detection, route-level code organisation and a 34-assertion Node smoke-test harness in CI. Deployed to GitHub Pages with service-worker offline caching and a web manifest.',
    tech: ['HTML5', 'Vanilla ES2025 JS', 'SVG Charts', 'CSS Custom Properties', 'Service Worker', 'PWA', 'GitHub Actions', 'WCAG 2.2 AA'],
    liveUrl: 'https://dlinacre.github.io/string-and-band/',
    repoUrl: 'https://github.com/DLinacre/string-and-band',
    live: true,
    artwork: '/projects/string-and-band.webp',
  },
  {
    name: 'AFTERGLOW ✦',
    artwork: '/projects/afterglow.webp',
    category: 'build',
    description: 'An original, endless light-painting game: you don\'t move a character — you leave light on. Hold the shutter and steer glowing pens to burn long-exposure trails onto a night sky. Features 10 brushes, 12 palettes, endless procedural shapes, a Daily Challenge, generative Web Audio, star-based unlocks, and a local gallery.',
    url: 'https://dlinacre.github.io/afterglow/',
    host: 'dlinacre.github.io/afterglow',
    tag: 'Featured · Live Game',
    role: 'Creator & Lead Developer',
    challenges: 'Inventing a genuinely novel core mechanic — persistent long-exposure light-painting as gameplay — then making it endless, teachable, and rewarding for long play sessions on a single mobile-friendly canvas with zero dependencies.',
    solution: 'Built a dependency-free HTML5 engine with three layered canvases and additive glow blending, a seeded PRNG for deterministic endless levels, a synthesised Web Audio ambient engine, snapshot-based undo/redo, and a registry architecture so brushes, palettes and shapes extend in a single line. Auto-deployed to GitHub Pages via GitHub Actions.',
    tech: ['JavaScript', 'HTML5 Canvas', 'Web Audio API', 'Procedural Generation', 'GitHub Actions', 'GitHub Pages'],
    liveUrl: 'https://dlinacre.github.io/afterglow/',
    repoUrl: 'https://github.com/DLinacre/afterglow',
    live: true,
  },
  {
    name: 'Pixel Heist 🚨',
    authorHandle: '@DLinacre',
    badgeLabel: 'Game · Live App',
    actionType: 'play',
    bannerImage: '/banners/pixel-heist.webp',
    category: 'design',
    description:
      'Cyberpunk stealth heist arcade game with Next.js 15, Phaser 3, and React 19. Features procedural neon vault levels, security lasers, hack terminals, and leaderboards.',
    url: 'https://dlinacre.github.io/pixel-heist/',
    host: 'dlinacre.github.io/pixel-heist',
    tag: 'Phaser 3 Game · Live',
    role: 'Game architect',
    challenges:
      'Combining Phaser 3 canvas scene management with React 19 UI overlays and procedural level generation.',
    solution:
      'Designed a hybrid React-Phaser architecture with custom laser collision physics, keycard hacking mechanics, and high scores.',
    tech: ['React 19', 'Phaser 3', 'TypeScript', 'Next.js 15'],
    artwork: '/projects/pixel-heist.webp',    liveUrl: 'https://dlinacre.github.io/pixel-heist/',
    repoUrl: 'https://github.com/DLinacre/pixel-heist',
    live: true,
  },
  {
    name: 'Slime Factory Tycoon 🟢',
    authorHandle: '@DLinacre',
    badgeLabel: 'Roblox · Source',
    actionType: 'play',
    bannerImage: '/banners/slime-factory-tycoon.webp',
    category: 'build',
    description:
      'Production-ready open-source Roblox idle-tycoon engine built in server-authoritative Luau with session-locked DataStores, pets engine, offline earnings, and interactive web demo.',
    url: 'https://dlinacre.github.io/slime-factory-tycoon/',
    host: 'dlinacre.github.io/slime-factory-tycoon',
    tag: 'Roblox Engine · Source',
    role: 'Lead game software engineer',
    challenges:
      'Preventing data duplication and race conditions in Roblox server-authoritative tycoon games.',
    solution:
      'Engineered a session-locked DataStore framework with automated CI testing, pets engine, offline calculations, and open-source codebase.',
    tech: ['Luau', 'Roblox Engine', 'DataStores', 'CI Simulator'],
    liveUrl: 'https://dlinacre.github.io/slime-factory-tycoon/',
    repoUrl: 'https://github.com/DLinacre/slime-factory-tycoon',
    live: true,
  },
  {
    name: 'GlitchArt Engine 🎨',
    authorHandle: '@DLinacre',
    badgeLabel: 'Creative · Live App',
    actionType: 'open',
    bannerImage: '/banners/glitchart-engine.webp',
    category: 'design',
    description:
      'Procedural digital glitch art engine & image manipulation laboratory with WebGL shaders, real-time parameter controls, canvas exporter, and glitch presets.',
    url: 'https://dlinacre.github.io/GlitchArt/',
    host: 'dlinacre.github.io/GlitchArt',
    tag: 'Creative Tool · Live',
    role: 'Creative technologist & shader engineer',
    challenges:
      'Real-time GPU shader manipulation of uploaded images and video streams in browser.',
    solution:
      'Developed custom WebGL shader pipelines for chromatic aberration, CRT scanlines, datamosh simulation, and high-res export.',
    tech: ['WebGL', 'Canvas 2D', 'TypeScript', 'Vite'],
    liveUrl: 'https://dlinacre.github.io/GlitchArt/',
    repoUrl: 'https://github.com/DLinacre/GlitchArt',
  },
  {
    name: 'Grumpy Guy AI ಠ_ಠ',
    authorHandle: '@DLinacre',
    badgeLabel: 'AI App · Live',
    actionType: 'open',
    bannerImage: '/banners/grumpy-guy.webp',
    artwork: '/projects/grumpy-guy-ai.webp',
    category: 'build',
    description: 'Your disagreeable AI copilot delivering motivation with complaints. Features custom tone selection (Dry, Brutal, Supportive), Web Speech synthesis, local storage persistence, and Cloudflare Worker fallback architecture.',
    url: 'https://dlinacre.github.io/grumpy-guy-ai/',
    host: 'dlinacre.github.io/grumpy-guy-ai',
    tag: 'Featured · Live v0.1.0',
    role: 'Creator & Lead Engineer',
    challenges: 'Developers and creators often face daily motivation slumps and need a fast, humorous, zero-friction reality check without bloat.',
    solution: 'Engineered a React 19 + TypeScript + Vite app with built-in Web Speech API voice synthesis, HSL dark-mode styling, Vitest coverage, and automated GitHub Actions CI/CD Pages deployment.',
    tech: ['React 19', 'TypeScript', 'Vite 7', 'Web Speech API', 'Vitest', 'GitHub Pages', 'Cloudflare Workers'],
    liveUrl: 'https://dlinacre.github.io/grumpy-guy-ai/',
    repoUrl: 'https://github.com/DLinacre/grumpy-guy-ai',
    live: true,
  },
  {
    name: "Nic's Food Decider 🍕",
    artwork: '/projects/nic-food-decider.webp',
    category: 'build',
    description: 'An intelligent, bias-weighted meal decision web application designed to solve dinner paralysis with cook & takeaway modes, custom filters, and decision history.',
    url: 'https://nic-food-decider.vercel.app',
    host: 'nic-food-decider.vercel.app',
    tag: 'Featured · Live v1.0.0',
    role: 'Full-stack developer & designer',
    challenges: 'Overcoming daily meal decision paralysis with an instant, bias-weighted decider and clean mobile-first UI.',
    solution: 'Engineered a Flask 3 & SQLite application with SQLAlchemy ORM, bcrypt auth, Pydantic validation, Jinja templates, and Vercel serverless deployment.',
    tech: ['Python', 'Flask', 'SQLAlchemy', 'SQLite', 'Vercel', 'Vanilla JS', 'CSS3', 'Pydantic'],
    liveUrl: 'https://nic-food-decider.vercel.app',
    repoUrl: 'https://github.com/DLinacre/nic-food-decider',
    live: true,
  },
  {
    name: 'Fleatment 🐱',
    authorHandle: '@DLinacre',
    badgeLabel: 'App · Live',
    actionType: 'open',
    bannerImage: '/banners/fleatment.webp',
    artwork: '/projects/fleatment.webp',    category: 'build',
    description:
      'An open-source UK cat flea & tick treatment finder, live delivered price index, active ingredient strength analyzer, and safety guide.',
    url: 'https://dlinacre.github.io/Fleatment/',
    host: 'dlinacre.github.io/Fleatment',
    tag: 'Featured · Live v1.0.0',
    role: 'Creator and product engineer',
    challenges:
      'Cat owners struggle to compare real delivered prices (with VAT & shipping) and identify dangerous canine pyrethroid ingredients.',
    solution:
      'Built an offline-first single-page web app with live JSON price auto-fetching, per-dose unit cost calculations, active ingredient matrix, and cost calculator.',
    tech: ['HTML5', 'Vanilla JS', 'JSON Feed', 'GitHub Pages', 'PWA'],
    liveUrl: 'https://dlinacre.github.io/Fleatment/',
    repoUrl: 'https://github.com/DLinacre/Fleatment',
    live: true,
  },
  {
    name: 'Personal OP Agent',
    authorHandle: '@DLinacre',
    badgeLabel: 'App · Live',
    actionType: 'open',
    bannerImage: '/banners/opagent.webp',
    artwork: '/projects/opagent.webp',    category: 'build',
    description:
      'A zero-setup, single-file HTML AI workspace and prompt controller running 100% locally in your browser with context history and model routing.',
    url: '/tools/opagent.html',
    host: 'linacre.site/tools/opagent.html',
    tag: 'Single-File App · Live',
    role: 'Creator and frontend architect',
    challenges:
      'Developers need an immediate, zero-build AI playground that runs offline and connects to models without multi-step server setup.',
    solution:
      'Engineered a standalone 170KB single-file HTML workspace with inline CSS, key storage, dynamic system prompts, and responsive streaming layout.',
    tech: ['HTML5', 'Vanilla JS', 'Tailwind CSS', 'Web Storage', 'AI Prompts'],
    liveUrl: '/tools/opagent.html',
    repoUrl: 'https://github.com/DLinacre/ev-backend',
    live: true,
  },
  {
    name: 'Arena Audit Prompt Builder',
    authorHandle: '@DLinacre',
    badgeLabel: 'App · Live',
    actionType: 'open',
    bannerImage: '/banners/arena-audit.webp',
    artwork: '/projects/a-audit.webp',    category: 'build',
    description:
      'A specialized browser audit tool for building systematic prompt checklists across UX, UI, SEO, Accessibility, and Security.',
    url: 'https://dlinacre.github.io/a-audit/',
    host: 'dlinacre.github.io/a-audit',
    tag: 'Single-File App · Live',
    role: 'Developer and prompt strategist',
    challenges:
      'Structured technical audits require exhaustive checklists that are easily customizable per product domain.',
    solution:
      'Built a modular single-page audit generator with instant search, category filtering, export formats, and zero third-party dependencies.',
    tech: ['HTML5', 'JavaScript', 'Tailwind CSS', 'GitHub Pages'],
    liveUrl: 'https://dlinacre.github.io/a-audit/',
    repoUrl: 'https://github.com/DLinacre/a-audit',
    live: true,
  },
  {
    name: 'APKHub 📱',
    artwork: '/projects/apkhub.webp',
    category: 'build',
    description: 'An open-source Android App Store & release indexer that discovers and downloads official APK releases from GitHub & F-Droid with QR installation support.',
    url: 'https://apkhub-alpha.vercel.app',
    host: 'apkhub-alpha.vercel.app',
    tag: 'Featured · App',
    role: 'Creator & Lead Engineer',
    challenges:
      'Sideloaded Android APK discovery requires transparent, verified source tracking without re-hosting binaries.',
    solution:
      'Engineered a React 19 single-file catalog interface with Python discovery indexers, QR instant-install flows, and direct release fetching.',
    tech: ['React 19', 'TypeScript', 'Vite 7', 'Python', 'Android APK', 'PWA'],
    liveUrl: 'https://apkhub-alpha.vercel.app',
    repoUrl: 'https://github.com/DLinacre/APKHub',
    live: true,
  },
  {
    name: 'OmniRoute LLM Engine',
    authorHandle: '@DLinacre',
    badgeLabel: 'DevOps · Source',
    actionType: 'open',
    bannerImage: '/banners/omniroute.webp',
    artwork: '/projects/omniroute.svg',    category: 'deploy',
    description:
      'Enterprise multi-provider AI model gateway & orchestration suite with fallback routing, load balancing, cost tracking, and streaming SSE endpoints.',
    url: 'https://github.com/DLinacre/OmniRoute-LLM',
    host: 'github.com/DLinacre/OmniRoute-LLM',
    tag: 'Featured · AI Gateway',
    role: 'Systems & AI Architect',
    challenges:
      'High-availability AI applications need automated fallback routing across Gemini, OpenAI, Claude, and local Ollama model providers.',
    solution:
      'Built a Next.js / TypeScript proxy gateway with Docker Compose orchestrators, Knip complexity checks, rate limiting, and real-time streaming sockets.',
    tech: ['Next.js', 'TypeScript', 'Docker', 'Gemini AI', 'OpenAI', 'Claude', 'Ollama'],
    repoUrl: 'https://github.com/DLinacre/OmniRoute-LLM',
  },
  {
    name: 'PokeGuru',
    authorHandle: '@DLinacre',
    badgeLabel: 'App · Live',
    actionType: 'open',
    bannerImage: '/banners/pokeguru.webp',
    artwork: '/projects/pokeguru.svg',    category: 'build',
    description:
      'A fast Pokémon TCG database with advanced search, UK prices in GBP, set history, chase-card discovery, and a local collection vault.',
    url: 'https://dlinacre.github.io/PokeGuru/',
    host: 'dlinacre.github.io/PokeGuru',
    tag: 'Featured · Live',
    role: 'Frontend and product engineer',
    challenges:
      'Large card catalogues need responsive search and useful market context without overwhelming collectors on mobile devices.',
    solution:
      'Built a typed React interface with route-based search, set browsing, GBP-first presentation, local collection tracking, and static GitHub Pages deployment.',
    tech: ['React', 'TypeScript', 'Vite', 'PWA', 'GitHub Pages'],
    liveUrl: 'https://dlinacre.github.io/PokeGuru/',
    repoUrl: 'https://github.com/DLinacre/PokeGuru',
    live: true,
  },
  {
    name: 'Apex POS',
    authorHandle: '@DLinacre',
    badgeLabel: 'App · Live',
    actionType: 'open',
    bannerImage: '/banners/apex-pos.webp',
    artwork: '/projects/apex-pos.svg',    category: 'build',
    description:
      'An offline-first point-of-sale system for the browser with register, stock, customers, expenses, receipts, and business reporting.',
    url: 'https://dlinacre.github.io/Apex-POS/',
    host: 'dlinacre.github.io/Apex-POS',
    tag: 'Offline App · Live',
    role: 'Product developer and maintainer',
    challenges:
      'Small operators need a usable register and stock system even when connectivity is poor and without sending business data to a third-party backend.',
    solution:
      'Kept the product client-side with IndexedDB offline storage, responsive register flows, inventory warnings, expense tracking, and receipt output.',
    tech: ['Vue 3', 'Dexie', 'IndexedDB', 'PWA', 'Offline-first'],
    liveUrl: 'https://dlinacre.github.io/Apex-POS/',
    repoUrl: 'https://github.com/DLinacre/Apex-POS',
    live: true,
  },
  {
    name: 'Mob Deals',
    authorHandle: '@DLinacre',
    badgeLabel: 'App · Live',
    actionType: 'open',
    bannerImage: '/banners/mob-deals.webp',
    artwork: '/projects/mob-deals.svg',    category: 'build',
    description:
      'A transparent UK SIM-only comparison and switching guide with 64 provider records, public source checks, and plain-English PAC/STAC help.',
    url: 'https://dlinacre.github.io/mob-deals/',
    host: 'dlinacre.github.io/mob-deals',
    tag: 'Featured · Live',
    role: 'Product designer and developer',
    challenges:
      'Mobile comparison sites often blur live prices, affiliate claims, and editorial data, making it hard for non-technical users to judge what is current.',
    solution:
      'Separated manually reviewed deal entries from automated reachability checks, linked every source, added clear disclaimers, and built an accessible number-switching flow.',
    tech: ['HTML', 'CSS', 'JavaScript', 'GitHub Actions', 'Accessibility'],
    liveUrl: 'https://dlinacre.github.io/mob-deals/',
    repoUrl: 'https://github.com/DLinacre/mob-deals',
    live: true,
  },
  {
    name: 'DKMA Monster',
    authorHandle: '@DLinacre',
    badgeLabel: 'Tools · Open Source',
    actionType: 'open',
    bannerImage: '/banners/dkma-monster.webp',
    artwork: '/projects/dkma-monster.svg',    category: 'build',
    description:
      'A practical Android background-app survival toolkit: searchable guidance for 15 OEM families plus CLI, desktop GUI, ADB, root, and Magisk options.',
    url: 'https://dlinacre.github.io/dkma-monster/',
    host: 'dlinacre.github.io/dkma-monster',
    tag: 'Featured · Open Source',
    role: 'Systems designer and maintainer',
    challenges:
      'Android manufacturers hide battery and autostart controls in different places, causing alarms, sync, and background services to stop silently.',
    solution:
      'Centralised OEM-specific guidance in one data model and reused it across a web guide and GUI tool (`/tools/dkma-gui.html`), with a no-root path for ordinary users.',
    tech: ['Android', 'ADB', 'Python', 'Kotlin', 'Magisk', 'HTML'],
    liveUrl: 'https://dlinacre.github.io/dkma-monster/',
    repoUrl: 'https://github.com/DLinacre/dkma-monster',
    live: true,
  },
  {
    name: 'Linacre Uninstaller',
    authorHandle: '@DLinacre',
    badgeLabel: 'Android · App',
    actionType: 'open',
    bannerImage: '/banners/linacre-uninstaller.webp',
    artwork: '/projects/linacre-uninstaller.svg',    category: 'build',
    description:
      'A downloadable Android cleanup app with searchable app labels, safety tiers, guided review, and a scoped batch-uninstall flow.',
    url: 'https://github.com/DLinacre/LinacreUninstaller/releases/latest',
    host: 'GitHub Releases',
    tag: 'Android · v1.3.1',
    role: 'Android developer and maintainer',
    challenges:
      'Debloat tools can encourage risky removals and often make sideloaded builds difficult to identify or trust.',
    solution:
      'Added explicit risk tiers, review-first interactions, clear launcher labels, a Material dark interface, and versioned APK releases with documented installation notes.',
    tech: ['Kotlin', 'Android', 'Material Design', 'GitHub Releases'],
    liveUrl: 'https://github.com/DLinacre/LinacreUninstaller/releases/latest',
    repoUrl: 'https://github.com/DLinacre/LinacreUninstaller',
  },
  {
    name: 'Linacre LLM Hub & Benchmarks',
    authorHandle: '@DLinacre',
    badgeLabel: 'Dashboard · Live',
    actionType: 'open',
    bannerImage: '/banners/linacre-llm-benchmarks.webp',
    artwork: '/projects/llm-hub.svg',    category: 'deploy',
    description:
      'Automated 24-hour LLM benchmark dashboard and model discovery super-app aggregating speed, pricing, and capability metrics.',
    url: 'https://dlinacre.github.io/Linacre-LLM-Benchmarks/',
    host: 'dlinacre.github.io/Linacre-LLM-Benchmarks',
    tag: 'Dashboard · Live',
    role: 'Platform developer',
    challenges: 'Model benchmarks move fast and are often spread across separate leaderboards.',
    solution:
      'Automated 24h scraping and aggregation scripts pushing JSON updates to a static GitHub Pages dashboard.',
    tech: ['JavaScript', 'Python', 'GitHub Actions', 'JSON'],
    liveUrl: 'https://dlinacre.github.io/Linacre-LLM-Benchmarks/',
    repoUrl: 'https://github.com/DLinacre/Linacre-LLM-Benchmarks',
  },
  {
    name: 'KushCloud',
    artwork: '/projects/kushcloud.svg',
    category: 'design',
    description: 'A polished one-tap browser game with four worlds, combo scoring, power-ups, unlockable cosmetics, synthesised audio, and an optional leaderboard.',
    url: 'https://dlinacre.github.io/KushCloud/',
    host: 'dlinacre.github.io/KushCloud',
    tag: 'Browser Game · Live',
    role: 'Game designer and frontend engineer',
    challenges: 'Deliver responsive arcade controls, progression, sound, and visual variety without relying on heavy external game assets.',
    solution: 'Used Canvas 2D, Web Audio, deterministic game state, adaptive quality, keyboard/touch controls, and a PWA-ready React shell.',
    tech: ['React', 'TypeScript', 'Canvas 2D', 'Web Audio', 'PWA'],
    liveUrl: 'https://dlinacre.github.io/KushCloud/',
    repoUrl: 'https://github.com/DLinacre/KushCloud',
    live: true,
  },
  {
    name: 'MyHub Dev Pipeline',
    authorHandle: '@DLinacre',
    badgeLabel: 'DevOps · Source',
    actionType: 'open',
    bannerImage: '/banners/myhub-pipeline.webp',
    artwork: '/projects/myhub-pipeline.svg',    category: 'deploy',
    description:
      'A documented Python DevOps reference project covering CI/CD, security checks, DORA-style metrics, anomaly detection, tests, and automated remediation experiments.',
    url: 'https://github.com/DLinacre/myhub-pipeline',
    host: 'github.com/DLinacre/myhub-pipeline',
    tag: 'DevOps · Source',
    role: 'Automation and platform engineer',
    challenges:
      'Pipeline concepts are often presented as disconnected YAML snippets rather than one inspectable system with tests, reports, and operational history.',
    solution:
      'Organised the workflow as a versioned Python project with architecture notes, CI, tests, security reports, release tags, and a repository-hosted demo recording.',
    tech: ['Python', 'GitHub Actions', 'CI/CD', 'Security', 'DORA Metrics'],
    repoUrl: 'https://github.com/DLinacre/myhub-pipeline',
  },
  {
    name: 'PayHip Scraper 🔎',
    artwork: '/projects/payhip-scraper.svg',
    category: 'build',
    description: 'Digital product intelligence for Payhip sellers: scrapes the live marketplace, scores every listing for opportunity, and generates Arena.ai prompts to build a better version.',
    url: 'https://payhipscraper-production.up.railway.app',
    host: 'payhipscraper-production.up.railway.app',
    tag: 'Featured · Live App',
    role: 'Creator and backend engineer',
    challenges: 'Payhip renders its marketplace client-side and its search matches any term in a phrase, so a naive scraper reads an empty page and a literal search returns unrelated products.',
    solution: 'Targets the marketplace search API directly, probes each term to narrow on the most selective one, then filters locally for full-phrase matches. Scores listings deterministically from real review volume, ratings and market size — no estimated sales figures.',
    tech: ['Node.js', 'Express', 'SQLite', 'Cheerio', 'Zod', 'Docker', 'Railway'],
    liveUrl: 'https://payhipscraper-production.up.railway.app',
    repoUrl: 'https://github.com/DLinacre/PayHip-Scraper',
    live: true
  },
  {
    name: 'Deasy Continuous Command Suite',
    authorHandle: '@DLinacre',
    badgeLabel: 'Desktop · Source',
    actionType: 'open',
    bannerImage: '/banners/deasy.webp',
    artwork: '/projects/deasy.svg',    category: 'deploy',
    description:
      'Continuous command suite and branch desktop manager for streamlined project deployment and local environment control.',
    url: 'https://github.com/DLinacre/Deasy',
    host: 'github.com/DLinacre/Deasy',
    tag: 'Desktop / CLI · Source',
    role: 'Creator and core engineer',
    challenges:
      'Managing multiple local development services and deployment branches requires an efficient desktop control interface.',
    solution:
      'Built a lightweight manager connecting CLI script orchestration, status monitoring, and electron deployment wrappers.',
    tech: ['TypeScript', 'Node.js', 'Electron', 'Vite'],
    repoUrl: 'https://github.com/DLinacre/Deasy',
  },
  {
    name: 'EV Bot & Voice Architecture',
    authorHandle: '@DLinacre',
    badgeLabel: 'Voice AI · Source',
    actionType: 'open',
    bannerImage: '/banners/ev-bot.webp',
    artwork: '/projects/ev-bot.svg',    category: 'deploy',
    description:
      'Voice assistant integration linking Alexa commands to desktop PC macro controls and Gemini-powered conversational responses.',
    url: 'https://github.com/DLinacre/ev-backend',
    host: 'github.com/DLinacre/ev-backend',
    tag: 'Voice AI · Backend Source',
    role: 'Systems engineer',
    challenges:
      'Low-latency Alexa skill handling and macro dispatch require strict signature validation and request rate limiting.',
    solution:
      'Engineered a FastAPI Python backend service with SQLite memory persistence, SSE event channels, and Alexa interaction models.',
    tech: ['FastAPI', 'Python', 'Alexa Skill Kit', 'Gemini AI', 'SQLite'],
    repoUrl: 'https://github.com/DLinacre/ev-backend',
  },
];

export const PROJECTS: Project[] = MANUAL_PROJECTS;

